ALTER TABLE "venues"
ADD COLUMN IF NOT EXISTS "hero_image_url" text,
ADD COLUMN IF NOT EXISTS "thumbnail_image_url" text,
ADD COLUMN IF NOT EXISTS "image_source" text DEFAULT 'nightly_fallback',
ADD COLUMN IF NOT EXISTS "gallery_image_urls_json" text,
ADD COLUMN IF NOT EXISTS "google_photo_references_json" text,
ADD COLUMN IF NOT EXISTS "google_cover_photo_reference" text,
ADD COLUMN IF NOT EXISTS "google_logo_image_url" text,
ADD COLUMN IF NOT EXISTS "official_website_url" text,
ADD COLUMN IF NOT EXISTS "official_website_image_url" text,
ADD COLUMN IF NOT EXISTS "official_website_icon_url" text,
ADD COLUMN IF NOT EXISTS "official_website_canonical_url" text,
ADD COLUMN IF NOT EXISTS "official_website_title" text,
ADD COLUMN IF NOT EXISTS "images_last_refreshed_at" timestamp,
ADD COLUMN IF NOT EXISTS "image_refresh_error" text;